/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class CadastroPaciente extends javax.swing.JFrame {
    public String nome, endereco, data, cpf,  telefone, email, senha;
    public String senhaconf;

  

    /**
     * Creates new form CadastroPaciente
     */
    public CadastroPaciente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        campoNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        campoCpf = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        campoEndereco = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        campoDatadeNascimento = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        campoTelefone = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        campoEmail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        campoSenha = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        campoSenhaConf = new javax.swing.JTextField();
        btCadastroPaciente = new javax.swing.JButton();
        btVoltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("VivaBem");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Nome completo: *");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 110, -1));

        campoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNomeActionPerformed(evt);
            }
        });
        getContentPane().add(campoNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 340, -1));

        jLabel4.setText("CPF: * ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, -1));

        campoCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCpfActionPerformed(evt);
            }
        });
        getContentPane().add(campoCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 340, -1));

        jLabel5.setText("Endereço: *");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));

        campoEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoEnderecoActionPerformed(evt);
            }
        });
        getContentPane().add(campoEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 340, -1));

        jLabel6.setText("Dada de nascimento: *");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, -1, -1));

        campoDatadeNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDatadeNascimentoActionPerformed(evt);
            }
        });
        getContentPane().add(campoDatadeNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 110, -1));

        jLabel7.setText("Telefone: *");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, -1, -1));
        getContentPane().add(campoTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 340, -1));

        jLabel8.setText("E-mail: *");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, -1, -1));
        getContentPane().add(campoEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, 340, -1));

        jLabel9.setText("senha: *");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, -1, -1));

        campoSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(campoSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 470, 340, -1));

        jLabel10.setText("Repita a senha: *");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 510, -1, -1));
        getContentPane().add(campoSenhaConf, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 530, 340, -1));

        btCadastroPaciente.setText("Cadastrar");
        btCadastroPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastroPacienteActionPerformed(evt);
            }
        });
        getContentPane().add(btCadastroPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 610, -1, -1));

        btVoltar.setText("Voltar");
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 610, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Cadastro de pacientes.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-330, -50, 1640, 760));

        pack();
    }// </editor-fold>                        

    private void campoNomeActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void campoCpfActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void campoEnderecoActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void campoDatadeNascimentoActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        // TODO add your handling code here:
    }                                                     

    private void campoSenhaActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void btCadastroPacienteActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        
        nome = campoNome.getText();
        if (!nome.matches("[a-zA-Z]+")) {
JOptionPane.showMessageDialog(null, "O nome deve conter apenas letras.", "Erro", JOptionPane.ERROR_MESSAGE);
return;
}       
        
        
        cpf = campoCpf.getText();
        if (!cpf.matches("\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}")) {
JOptionPane.showMessageDialog(null, "O CPF deve estar no formato 000.000.000-00.", "Erro", JOptionPane.ERROR_MESSAGE);
return;}
	endereco = campoEndereco.getText();
        data = campoDatadeNascimento.getText();
        if (!data.matches("\\d{2}/\\d{2}/\\d{4}")) {
JOptionPane.showMessageDialog(null, "A data deve estar no formato dd/mm/aaaa.", "Erro", JOptionPane.ERROR_MESSAGE);
return;}
	telefone = campoTelefone.getText();
	email = campoEmail.getText();
        senha =campoSenha.getText();
        senhaconf = campoSenhaConf.getText();
	View.CaixaDeAviso aviso = new CaixaDeAviso();
        if(senha.equals("")|| cpf.equals("")||email.equals("")){
        aviso.setLocationRelativeTo(null);
        aviso.show(true);
    }else if(campoSenhaConf.getText() == null ? campoSenha.getText() != null : !campoSenhaConf.getText().equals(campoSenha.getText())){
                            aviso.setLocationRelativeTo(null);
                            aviso.show(true);
                }
        else{			
	try
        {
		Class.forName("com.mysql.cj.jdbc.Driver");
		Connection con = DriverManager.getConnection("jdbc:mysql://localhost/acelera","root","");
		Statement stm = con.createStatement();
		if(stm.executeUpdate("INSERT into cadastro_paciente values('"+nome+"','"+cpf+"','"+endereco+"','"+data+"','"+telefone+"','"+email+"','"+senha+"')")!=0)
		{
			JOptionPane.showMessageDialog(null,"Cadastro realizado com sucesso!!!","Sucesso",JOptionPane.INFORMATION_MESSAGE);
			campoNome.setText("");
                        campoCpf.setText("");
                        campoDatadeNascimento.setText("");                        
			campoEndereco.setText("");
			campoTelefone.setText("");
			campoEmail.setText("");
                        campoSenha.setText("");
		}
		else
		{
			JOptionPane.showMessageDialog(null,"Erro para realizar o cadastro!!!","Erro",JOptionPane.ERROR_MESSAGE);
		}
	}
	catch(ClassNotFoundException ex)
	{
		JOptionPane.showMessageDialog(null,ex.getMessage(),"Erro",JOptionPane.ERROR_MESSAGE);
	}
	catch(SQLException ex)
	{
		JOptionPane.showMessageDialog(null,ex.getMessage(),"Erro",JOptionPane.ERROR_MESSAGE);
	}

             
     
    }                                                  
    }
    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {                                         
        Login log = new Login();
        log.setLocationRelativeTo(null);
        log.show();
        this.setVisible(false);     
        
        
        
    }                                        

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify                     
    private javax.swing.JButton btCadastroPaciente;
    private javax.swing.JButton btVoltar;
    private javax.swing.JTextField campoCpf = new JFormattedTextField(new MaskFormatter("###.###.###-##"));;
    private javax.swing.JTextField campoDatadeNascimento;
    private javax.swing.JTextField campoEmail;
    private javax.swing.JTextField campoEndereco;
    private javax.swing.JTextField campoNome;
    private javax.swing.JTextField campoSenha;
    private javax.swing.JTextField campoSenhaConf;
    private javax.swing.JTextField campoTelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration                   
}
