/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;

/**
 *
 * @author User
 * Tela de Boas Vindas
 */
public class QuemSomos extends javax.swing.JFrame {

    /**
     * Creates new form QuemSomos
     */
    public QuemSomos() {
        initComponents();
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btVoltar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("VivaBem");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setColumns(20);
        jTextArea1.setRows(10);
        jTextArea1.setText("Equipe do VivaBem\n\n Seja bem-vindo ao universo da nossa equipe dedicada ao bem-estar e saúde! \n É com imenso prazer que apresentamos a você nossos serviços, desenvolvidos com o objetivo principal de proporcionar \nsoluções interessantes e personalizadas para melhorar sua qualidade de vida.\n\n Nossa equipe é composta por profissionais altamente capacitados e apaixonados por cuidar do bem-estar dos nossos clientes.\n Valorizamos cada indivíduo como único, reconhecendo suas necessidades e preocupações específicas. Com abordagens inovadoras \ne uma visão holística, trabalhamos em conjunto para encontrar as melhores soluções para você.\n\nPriorizamos sua saúde física, mental e emocional, entendendo que todas as áreas estão intrinsecamente conectadas.\n Acreditamos que uma vida plena é alcançada quando corpo, mente e espírito estão em equilíbrio. Com base nessa filosofia, oferecemos \numa ampla gama de serviços projetados para atender às suas demandas e objetivos individuais.\n\n\nAlém disso, estamos constantemente atualizados com as últimas tendências e pesquisas relacionadas à saúde e bem-estar. \nAssim, podemos fornecer a você as informações mais atualizadas e eficazes para ajudar a tomar decisões informadas sobre seu estilo de vida.\n\nEstamos ansiosos para embarcar nesta jornada com você, proporcionando soluções interessantes e eficazes para seu bem-estar e saúde. \nEntre em contato conosco e agende uma consulta inicial para discutirmos como podemos melhor atender às suas necessidades.\n\nSua saúde é nossa prioridade e nossa maior satisfação é vê-lo alcançar uma vida plena e feliz. Junte-se a nós nessa busca \npelo equilíbrio e bem-estar duradouros!\n\nAtenciosamente, Equipe do VivaBem.\n");
        jTextArea1.setFocusable(false);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 810, 390));

        btVoltar.setBackground(new java.awt.Color(175, 217, 159));
        btVoltar.setText("Voltar");
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 630, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Tela de boas vindas.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-490, -320, 1340, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_btVoltarActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btVoltar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
         URL url = this.getClass().getResource("/Imagens/heart.png");
         Image imgTitulo = Toolkit.getDefaultToolkit().getImage(url);
         this.setIconImage(imgTitulo);
    }
}
