/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JTextField;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author User
 */
public class TelaPrincipalMedico extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipalMedico
     */
    public TelaPrincipalMedico() {
        initComponents();
        setIconImage();
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btUser = new javax.swing.JButton();
        btConsultarDados = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("VivaBem ");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/do-utilizador (1).png"))); // NOI18N
        btUser.setText("Meu Usuário");
        btUser.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btUser.setContentAreaFilled(false);
        btUser.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUserActionPerformed(evt);
            }
        });
        btUser.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                btUserPropertyChange(evt);
            }
        });
        getContentPane().add(btUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 40, 350, 70));

        btConsultarDados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/local-na-rede-internet.png"))); // NOI18N
        btConsultarDados.setText("Consultas agendadas");
        btConsultarDados.setBorderPainted(false);
        btConsultarDados.setContentAreaFilled(false);
        btConsultarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarDadosActionPerformed(evt);
            }
        });
        getContentPane().add(btConsultarDados, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, -1, 40));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/paciente.png"))); // NOI18N
        jButton4.setText("Meus Pacientes");
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, -1, 40));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("Voltar");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 770, 140, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Principal Medico.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 810));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cadastro (1).png"))); // NOI18N
        jButton1.setText("Consulta Pacientes");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, -1, -1));

        jPanel1.setPreferredSize(new java.awt.Dimension(400, 300));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1415, 860, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -250, 1430, 210));

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/botao-de-menu-de-tres-linhas-horizontais.png"))); // NOI18N
        jMenu2.setText("Menu");

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/pc.png"))); // NOI18N
        jMenu4.setText("Consultas");

        jMenuItem1.setBackground(new java.awt.Color(175, 217, 159));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/medico_1.png"))); // NOI18N
        jMenuItem1.setText("Consulta Pacientes");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        jMenu2.add(jMenu4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        RelatorioPessoas mostrar = new RelatorioPessoas();
        mostrar.setLocationRelativeTo(null);
        mostrar.show();
        
        
    }//GEN-LAST:event_jButton1ActionPerformed
//Botão que chama a tela Principal
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int x;
        UIManager.put("OptionPane.cancelButtonText", "Cancelar"); 
         UIManager.put("OptionPane.noButtonText", "Não"); 
         UIManager.put("OptionPane.yesButtonText", "Sim");
        x = JOptionPane.showConfirmDialog(null, "Deseja Sair do VivaBem ?", null, JOptionPane.YES_NO_CANCEL_OPTION);
	int Sim = 0;
	int no = 1;
	int cancel = 2;
	if (x == 0) {
	Login log = new Login();
        log.setLocationRelativeTo(null);
        log.show();
        this.setVisible(false);	//aqui você colocar a lógico
	}
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btUserActionPerformed
    //Botão que chama a tela Relatório Pessoas
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        RelatorioPessoas novo = new RelatorioPessoas();
        novo.setLocationRelativeTo(null);
        novo.show();
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    //Botão que chama a tela Dados da Consulta
    private void btConsultarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarDadosActionPerformed
       DadosConsultasMedico dados = new DadosConsultasMedico();
       dados.setLocationRelativeTo(null);
       dados.show();    
    }//GEN-LAST:event_btConsultarDadosActionPerformed
    //Botão que chama Relatório Pessoas
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        RelatorioPessoas tela = new RelatorioPessoas();
        tela.setLocationRelativeTo(null);
        tela.show();
    }//GEN-LAST:event_jButton4ActionPerformed
    //Botão User que chama a variavel teste string da tela de Login
    private void btUserPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_btUserPropertyChange
       btUser.setText(View.Login.teste);
    }//GEN-LAST:event_btUserPropertyChange

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btConsultarDados;
    private javax.swing.JButton btUser;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    //Método que chama Icone do Sistema "Heart"
    private void setIconImage() {
         URL url = this.getClass().getResource("/Imagens/heart.png");
         Image imgTitulo = Toolkit.getDefaultToolkit().getImage(url);
         this.setIconImage(imgTitulo);
    }
}
