/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author aluno
 */
public class TelaPrincipal extends javax.swing.JFrame {
public String Nome;

    public TelaPrincipal() {
        initComponents();
        setIconImage();
        
    }
       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        btConsulta = new javax.swing.JButton();
        btUser = new javax.swing.JButton();
        btProfissional = new javax.swing.JButton();
        btPacientes = new javax.swing.JButton();
        btMedicos1 = new javax.swing.JButton();
        btPesquisaPaciente = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        btAlterarMedicos = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("VivaBem");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Voltar");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 770, 140, 40));

        btConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/pc.png"))); // NOI18N
        btConsulta.setText("Minhas Consultas");
        btConsulta.setBorderPainted(false);
        btConsulta.setContentAreaFilled(false);
        btConsulta.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultaActionPerformed(evt);
            }
        });
        getContentPane().add(btConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 180, 40));

        btUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/do-utilizador (1).png"))); // NOI18N
        btUser.setText("Meu Usuário");
        btUser.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btUser.setContentAreaFilled(false);
        btUser.setDefaultCapable(false);
        btUser.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUserActionPerformed(evt);
            }
        });
        btUser.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                btUserPropertyChange(evt);
            }
        });
        getContentPane().add(btUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 30, 360, 70));

        btProfissional.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/profissional.png"))); // NOI18N
        btProfissional.setText("Profissionais");
        btProfissional.setBorderPainted(false);
        btProfissional.setContentAreaFilled(false);
        btProfissional.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btProfissional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProfissionalActionPerformed(evt);
            }
        });
        getContentPane().add(btProfissional, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 170, 40));

        btPacientes.setBackground(new java.awt.Color(153, 255, 153));
        btPacientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cadastro (1).png"))); // NOI18N
        btPacientes.setText("Cadastrar Pacientes");
        btPacientes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btPacientes.setBorderPainted(false);
        btPacientes.setContentAreaFilled(false);
        btPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPacientesActionPerformed(evt);
            }
        });
        getContentPane().add(btPacientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, 180, 40));

        btMedicos1.setBackground(new java.awt.Color(153, 255, 153));
        btMedicos1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/agenda (1).png"))); // NOI18N
        btMedicos1.setText("Agendar Consultas");
        btMedicos1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btMedicos1.setBorderPainted(false);
        btMedicos1.setContentAreaFilled(false);
        btMedicos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMedicos1ActionPerformed(evt);
            }
        });
        getContentPane().add(btMedicos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 160, 40));

        btPesquisaPaciente.setBackground(new java.awt.Color(153, 255, 153));
        btPesquisaPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/lupa.png"))); // NOI18N
        btPesquisaPaciente.setText("Pesquisar Pacientes");
        btPesquisaPaciente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btPesquisaPaciente.setBorderPainted(false);
        btPesquisaPaciente.setContentAreaFilled(false);
        btPesquisaPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisaPacienteActionPerformed(evt);
            }
        });
        getContentPane().add(btPesquisaPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 150, 160, 40));

        btAlterar.setBackground(new java.awt.Color(153, 255, 153));
        btAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/atualizar (1).png"))); // NOI18N
        btAlterar.setText("Alterar Cadastro Paciente");
        btAlterar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btAlterar.setBorderPainted(false);
        btAlterar.setContentAreaFilled(false);
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(btAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 150, 190, 40));

        btAlterarMedicos.setBackground(new java.awt.Color(153, 255, 153));
        btAlterarMedicos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/atualizar (1).png"))); // NOI18N
        btAlterarMedicos.setText("Alterar Cadastro Medico");
        btAlterarMedicos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btAlterarMedicos.setBorderPainted(false);
        btAlterarMedicos.setContentAreaFilled(false);
        btAlterarMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarMedicosActionPerformed(evt);
            }
        });
        getContentPane().add(btAlterarMedicos, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 150, 180, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Principal Atendente.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 810));

        jMenu2.setBackground(new java.awt.Color(153, 255, 153));
        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/botao-de-menu-de-tres-linhas-horizontais.png"))); // NOI18N
        jMenu2.setText("Menu");

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/pc.png"))); // NOI18N
        jMenu4.setText("Consultas");

        jMenuItem3.setBackground(new java.awt.Color(175, 217, 159));
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/medico_1.png"))); // NOI18N
        jMenuItem3.setText("Pacientes");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem3);

        jMenu2.add(jMenu4);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/profissional.png"))); // NOI18N
        jMenu5.setText("Profissionais ");

        jMenuItem1.setBackground(new java.awt.Color(175, 217, 159));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/medico (1)_1.png"))); // NOI18N
        jMenuItem1.setText("Médicos");
        jMenuItem1.setBorderPainted(false);
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem1);

        jMenuItem2.setBackground(new java.awt.Color(175, 217, 159));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/relatorio-de-seo.png"))); // NOI18N
        jMenuItem2.setText("Relatório Médicos");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem2);

        jMenuItem5.setBackground(new java.awt.Color(175, 217, 159));
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cadastro (1).png"))); // NOI18N
        jMenuItem5.setText("Cadastrar Funcionários");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem5);

        jMenuItem4.setBackground(new java.awt.Color(175, 217, 159));
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/conjunto-de-setas-de-sincronizacao.png"))); // NOI18N
        jMenuItem4.setText("Alteração de Cadastro Funcionários");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem4);

        jMenuItem6.setBackground(new java.awt.Color(175, 217, 159));
        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/local-na-rede-internet.png"))); // NOI18N
        jMenuItem6.setText("Cadastrar Médicos");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem6);

        jMenu2.add(jMenu5);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Botão Voltar para o Login
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         int x;
         UIManager.put("OptionPane.cancelButtonText", "Cancelar"); 
         UIManager.put("OptionPane.noButtonText", "Não"); 
         UIManager.put("OptionPane.yesButtonText", "Sim");
        x = JOptionPane.showConfirmDialog(null, "Deseja Sair do VivaBem ?", null, JOptionPane.YES_NO_CANCEL_OPTION);
	int Sim = 0;
	int no = 1;
	int cancel = 2;
	if (x == 0) {
	Login log = new Login();
        log.setLocationRelativeTo(null);
        log.show();
        this.setVisible(false);	
	}
        
    }//GEN-LAST:event_jButton1ActionPerformed
    //Botão dados Consulta
    private void btConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultaActionPerformed
        DadosConsultas dados = new DadosConsultas();
        dados.setLocationRelativeTo(null);
        dados.show();
    }//GEN-LAST:event_btConsultaActionPerformed

    private void btUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUserActionPerformed
 

       
       
    }//GEN-LAST:event_btUserActionPerformed
    //Botão Dados Médicos
    private void btProfissionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProfissionalActionPerformed
     View.DadosMedicos medicos = new DadosMedicos();
     medicos.setLocationRelativeTo(null);
     medicos.show();
     medicos.setLocationRelativeTo(null);
     
                      
    }//GEN-LAST:event_btProfissionalActionPerformed
    //Opção do Menu que chama Dados Medicos
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        DadosMedicos dados = new DadosMedicos();
        dados.setLocationRelativeTo(null);
        dados.show();
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    //Opção do Menu que chama a Tela Relatório Médico
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        RelatorioMedicos dados = new RelatorioMedicos();
        dados.setLocationRelativeTo(null);
        dados.show();
    }//GEN-LAST:event_jMenuItem2ActionPerformed
    // Opção que chama a Tela Dados Pessoas
    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        RelatorioPessoas dados = new RelatorioPessoas();
        dados.setLocationRelativeTo(null);
        dados.show();
    }//GEN-LAST:event_jMenuItem3ActionPerformed
    //Botão que chama Cadastro paciente
    private void btPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPacientesActionPerformed
        CadastroPaciente paciente = new CadastroPaciente();
        paciente.setLocationRelativeTo(null);
        paciente.show();
    }//GEN-LAST:event_btPacientesActionPerformed
    //Botão que chama a Agenda Marcar Consultas
    private void btMedicos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMedicos1ActionPerformed
        Agenda agenda = new Agenda();
        agenda.setLocationRelativeTo(null);
        agenda.show();
    }//GEN-LAST:event_btMedicos1ActionPerformed
    //Botão que chama a tela Mostrar Paciente
    private void btPesquisaPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisaPacienteActionPerformed
        MostarPaciente mostrar = new MostarPaciente();
        mostrar.setLocationRelativeTo(null);
        mostrar.show();
    }//GEN-LAST:event_btPesquisaPacienteActionPerformed
    //Mudança do Texto do Botão bt.User com a String salva na tela de Login "teste"
    private void btUserPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_btUserPropertyChange
           btUser.setText(View.Login.teste);

     }//GEN-LAST:event_btUserPropertyChange
    //Botão que chama a Tela Cadastro de Funcionários
    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        CadastroFuncionarios funcionario = new CadastroFuncionarios();
        funcionario.setLocationRelativeTo(null);
        funcionario.show();
    }//GEN-LAST:event_jMenuItem5ActionPerformed
    //Botão que chama a tela Cadastro de Médicos
    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        CadastroDeProfissionais medico = new CadastroDeProfissionais();
        medico.setLocationRelativeTo(null);
        medico.show();
    }//GEN-LAST:event_jMenuItem6ActionPerformed
    //Botão que chama a Tela Alterar paciente
    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
       TelaDeAlterar tela = new TelaDeAlterar();
       tela.setLocationRelativeTo(null);
       tela.show();
    }//GEN-LAST:event_btAlterarActionPerformed
    //Botão que chama a tela Alterar médicos
    private void btAlterarMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarMedicosActionPerformed
        TelaDeAlterarMedicos medicos = new TelaDeAlterarMedicos();
        medicos.setLocationRelativeTo(null);
        medicos.show();
    }//GEN-LAST:event_btAlterarMedicosActionPerformed
    //Botão que chama a tela alterar profissionais
    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        TelaDeAlterarProfissionais tela = new TelaDeAlterarProfissionais();
        tela.setLocationRelativeTo(null);
        tela.show();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btAlterarMedicos;
    private javax.swing.JButton btConsulta;
    private javax.swing.JButton btMedicos1;
    private javax.swing.JButton btPacientes;
    private javax.swing.JButton btPesquisaPaciente;
    private javax.swing.JButton btProfissional;
    private javax.swing.JButton btUser;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    // End of variables declaration//GEN-END:variables
    //Método que chama o icone "heart.png"
    private void setIconImage() {
        URL url = this.getClass().getResource("/Imagens/heart.png");
         Image imgTitulo = Toolkit.getDefaultToolkit().getImage(url);
         this.setIconImage(imgTitulo);
    }
}
