/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author User
 */
public class TelaDeAlterarMedicos extends javax.swing.JFrame {
    public String nome, endereco, data, cpf,  telefone, email, senha, crm;
    public String senhaconf;
    public String dados;
    public String nomeAtual, enderecoAtual, CpfAtual,telefoneAtual,emailAtual, dataAtual, crmAtual;
    public String novoNome, novoEndereco, novoCpf, novoTelefone, novoEmail, novaData, novoCRM;
    boolean status = false;
  

    /**
     * Creates new form CadastroPaciente
     * Tela de Alterar Dados médicos
     */
    public TelaDeAlterarMedicos() {
        initComponents();
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        campoNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        camponovoEndereco = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        camponovoEmail = new javax.swing.JTextField();
        btMostrarPacientes = new javax.swing.JButton();
        btVoltar = new javax.swing.JButton();
        camponovoCpf = new javax.swing.JFormattedTextField();
        camponovoDatadeNascimento = new javax.swing.JFormattedTextField();
        camponovoTelefone = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btAlterar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        CRMnovocampo = new javax.swing.JTextField();
        btDeletarMedicos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("VivaBem");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Nome completo: *");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 110, -1));

        campoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNomeActionPerformed(evt);
            }
        });
        getContentPane().add(campoNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 340, -1));

        jLabel4.setText("CPF: * ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, -1));

        jLabel5.setText("Endereço: *");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));

        camponovoEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                camponovoEnderecoActionPerformed(evt);
            }
        });
        getContentPane().add(camponovoEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 340, -1));

        jLabel6.setText("Dada de nascimento: *");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, -1, -1));

        jLabel7.setText("Telefone: *");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, -1, -1));

        jLabel8.setText("E-mail: *");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, -1, -1));
        getContentPane().add(camponovoEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 470, 340, -1));

        btMostrarPacientes.setText("Mostrar Médico");
        btMostrarPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMostrarPacientesActionPerformed(evt);
            }
        });
        getContentPane().add(btMostrarPacientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 560, 130, 30));

        btVoltar.setText("Voltar");
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 610, 130, 30));

        try {
            camponovoCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(camponovoCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 340, -1));

        try {
            camponovoDatadeNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(camponovoDatadeNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 110, -1));

        try {
            camponovoTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ##### - ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(camponovoTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, 110, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Digite o Nome:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Alteração de Cadastro Médico");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        btAlterar.setText("Alterar Cadastro");
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(btAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 560, 130, 30));

        jLabel10.setText("CRM:*");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, -1, -1));
        getContentPane().add(CRMnovocampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 140, -1));

        btDeletarMedicos.setText("Deletar");
        btDeletarMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeletarMedicosActionPerformed(evt);
            }
        });
        getContentPane().add(btDeletarMedicos, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 610, 130, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Cadastro de pacientes.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-330, -50, 1640, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNomeActionPerformed

    private void camponovoEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_camponovoEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_camponovoEnderecoActionPerformed
    //Botão Mostrar dados Medicos
    private void btMostrarPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMostrarPacientesActionPerformed
     
				
				
	try
	{
               Class.forName("com.mysql.cj.jdbc.Driver");
               Connection con = DriverManager.getConnection("jdbc:mysql://localhost/acelera","root","");
               Statement stm = con.createStatement();
               ResultSet res = stm.executeQuery("SELECT * from cadastro_medico");
					
                nome = campoNome.getText();
                
		while(res.next())
		{
		   nomeAtual = res.getString("nome");
		   
                   if(nomeAtual.compareTo(nome)==0)
		   {
			  CpfAtual = res.getString("cpf");
                          enderecoAtual = res.getString("endereco");
                          dataAtual = res.getString("data_de_nascimento");                          
			  telefoneAtual = res.getString("telefone");
                          crmAtual = res.getString("CRM");
			  emailAtual = res.getString("email");
			  status=false;						  
		   }					   			   
		}            
		
			camponovoCpf.setText(CpfAtual);
                        camponovoEndereco.setText(enderecoAtual);
			camponovoDatadeNascimento.setText(dataAtual);
                        camponovoTelefone.setText(telefoneAtual);
                        CRMnovocampo.setText(crmAtual);
			camponovoEmail.setText(emailAtual);
                        status=true;
		
		if(status == false)
		{
			JOptionPane.showMessageDialog(null,"Nome: "+nome+" não encontrado!!!","Erro",JOptionPane.ERROR_MESSAGE);
		}
	}
	catch(ClassNotFoundException ex)
	{
		JOptionPane.showMessageDialog(null,ex.getMessage(),"Erro",JOptionPane.ERROR_MESSAGE);
	}
	catch(SQLException ex)
	{
		JOptionPane.showMessageDialog(null,ex.getMessage(),"Erro",JOptionPane.ERROR_MESSAGE);
	}
       
    }//GEN-LAST:event_btMostrarPacientesActionPerformed
 //Botão Voltar
    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
            dispose();  
        
        
        
    }//GEN-LAST:event_btVoltarActionPerformed
    //Botão Alterar dados Médicos no cadastro_medico 
    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
    int y;
         UIManager.put("OptionPane.cancelButtonText", "Cancelar"); 
         UIManager.put("OptionPane.noButtonText", "Não"); 
         UIManager.put("OptionPane.yesButtonText", "Sim");    
    y = JOptionPane.showConfirmDialog(null, "Tem Certeza que quer Continuar com a Alteração?", null, JOptionPane.YES_NO_CANCEL_OPTION);
	int Sim = 0;
	int no = 1;
	int cancel = 2;
	if (y == 0){ 
        String classeDriver = "com.mysql.cj.jdbc.Driver";
	String stringConexao = "jdbc:mysql://localhost/acelera";
	String login = "root";
	String senha = "";
	Connection con;
	String sql;
	            
	novoNome = campoNome.getText();
        novoCpf = camponovoCpf.getText();
	novoEndereco = camponovoEndereco.getText();
        novaData = camponovoDatadeNascimento.getText();
	novoTelefone = camponovoTelefone.getText();
        novoCRM = CRMnovocampo.getText();
	novoEmail = camponovoEmail.getText();
	            
	con=null;
	sql = "SELECT * FROM cadastro_medico";

	try
	{
	    Class.forName(classeDriver);
	    con = DriverManager.getConnection(stringConexao, login, senha);
	    PreparedStatement stmt = con.prepareStatement(sql);

	    int x=stmt.executeUpdate("UPDATE cadastro_medico SET nome='"+novoNome+"',cpf='"+novoCpf+"'," +
	         "endereco='"+novoEndereco+"',data_de_nascimento='"+novaData+"', telefone='"+novoTelefone+"',CRM='"+novoCRM+"'," +
	         "email='"+novoEmail+"' WHERE nome='"+nome+"';");
            if (x == 1 )
                JOptionPane.showMessageDialog(null,"Cadastro atualizado com sucesso!","",JOptionPane.INFORMATION_MESSAGE);
        }
	catch(SQLException ex)
	{
	   JOptionPane.showMessageDialog(null,ex.getMessage(),"Erro",JOptionPane.INFORMATION_MESSAGE);
	}
	catch(ClassNotFoundException ex)
	{
	   JOptionPane.showMessageDialog(null,ex.getMessage(),"Erro",JOptionPane.INFORMATION_MESSAGE);
	}}
    }//GEN-LAST:event_btAlterarActionPerformed
    //Botão que chama a Tela Deletar
    private void btDeletarMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeletarMedicosActionPerformed
      DeleteMedico delete = new DeleteMedico();
      delete.show();
              
    }//GEN-LAST:event_btDeletarMedicosActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CRMnovocampo;
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btDeletarMedicos;
    private javax.swing.JButton btMostrarPacientes;
    private javax.swing.JButton btVoltar;
    private javax.swing.JTextField campoNome;
    private javax.swing.JFormattedTextField camponovoCpf;
    private javax.swing.JFormattedTextField camponovoDatadeNascimento;
    private javax.swing.JTextField camponovoEmail;
    private javax.swing.JTextField camponovoEndereco;
    private javax.swing.JFormattedTextField camponovoTelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
    //Método que chama o Icone Heart.png 
    private void setIcon() {
        URL url = this.getClass().getResource("/Imagens/heart.png");
         Image imgTitulo = Toolkit.getDefaultToolkit().getImage(url);
         this.setIconImage(imgTitulo);
    }
}
